name: CI
on:
push:
branches: [main, dev]
pull_request:
branches: [main, dev]

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4

 - name: Setup Node 24.6 and PNPM
    uses: actions/setup-node@v4
    with:
      node-version: '24.6.0'
      cache: 'pnpm'

  - name: Enable Corepack
    run: corepack enable

  - name: Install deps
    run: pnpm install --frozen-lockfile

  - name: Lint
    run: pnpm lint -- --dir src

  - name: Typecheck
    run: pnpm exec tsc --noEmit

  - name: Build
    run: pnpm build